### ISSUE TITLE
Proposal: prefer setf (generalized variables) over setter functions

### ISSUE THREAD

**Issue by skeeto** [bbatsov/emacs-lisp-style-guide#10]
This one is probably controversial. Emacs 24.3 took setf out of the cl package (at the same time renaming it to cl-lib) and introduced it to the Emacs Lisp core as *generalized variables* (gv). Many of the "places" in Emacs that hold values can be mutated with the setf family of functions. For example,

~~~el
(setf somevar :foo)
(setf (point) (point-max))
(setf (buffer-name) "*scratch*")
(setf (cdr somelist) (list 2 3 4))
~~~

`setq` is a vestigial feature leftover from Emacs Lisp's dynamic scoping days. It's no longer conceptually a wrapper for `set`, and "set quoted" [doesn't really make sense in lexical scope](http://random-state.net/files/nikodemus-cl-faq.html#set-setq-and-setf----whats-the-difference-which-one-should-
i-use).

The big advantage with generalized variables is that APIs no longer need to include a bunch of special setter functions for every possible place. The getter and its natural setf complement cover everything. It also composes with the other generalized setters (`rotatef`, `incf`, etc.). 

On the other hand, this change only happened in the very latest stable release (24.3, March 2013). Even though it's over a year old, many people still aren't quite up to date. The change was made in a not entirely backwards-compatible way: in Emacs 24.3 you're not supposed to `(require 'cl)` in new code, but you can use `setf` without it. Prior to this you had to require cl (even if just at compile time) before using `setf`. So perhaps there needs to be more time before it's appropriate to prefer generalized veriables.

**Comment by PythonNut** [comment]
@lunaryorn @technomancy would you condone using generalized variables instead of their backing setters/getters? i.e. `(setf (car ... ) ...)` instead of `(setcar ...)`? If not in the general case, maybe in the case where it's actually useful.

**Comment by Bruce-Connor** [comment]
@PythonNut Is `setf` available in emacs 24.1? Or do you need to use `cl-setf` in that case?

**Comment by PythonNut** [comment]
@Bruce-Connor `setf` should be available in the `cl` package; however its use discouraged. Looking at the source for `cl-lib-0.5`, I don't see any `setf` or equivalent macro, and no such macro exists in my `24.4` copy of `cl-lib` (version `1.0`).

That said, I'm a very new emacs user (about a year old). I wasn't around for those releases so my information isn't very solid.

**Comment by Bruce-Connor** [comment]
@PythonNut 
I just tested, indeed `setf` is only available as part of `cl` (or `cl-lib`) on earlier Emacs. In that case, that's not something that can be generally recommended. If you're writing a package that supports 24.1, you would have to add a dependency just for the sake of using `setf`, which is kind of pointless if you're only using `setf` as a glorified `setcar/cdr`.

If your package is only designed for 24.4, or if you already have `cl-lib` as a dependency, then `setf` vs `setcar/cdr` is a matter of preference. But I'd say that's a little specific for the style guide ATM. I don't think there's a reason to encourage it (yet).

FWIW, regarding usage inside Emacs core, `setf` and generalized variables have been actively used on a few places (at least `url.el` and `package.el` that I'm aware of).

**Comment by dgutov** [comment]
While `setf` is used a lot in `package.el`, none of its usages could be easily replaced by `setq`. Same in `lisp/url/*`.

Using `setf` for everything is a CL thing, right? While it looks cute and (maybe more) consistent, it looks fairly unlikely that Emacs core is going to adopt this practice anytime soon. So it's a -1 from me.

**Comment by purcell** [comment]
> Using setf for everything is a CL thing, right? While it looks cute and (maybe more) consistent, it looks fairly unlikely that Emacs core is going to adopt this practice anytime soon. So it's a -1 from me.

Yes, -1 from me too. `setq` is an easy-to-understand primitive, and I think it's a mistake to tell people to generally prefer `setf`, particularly when there are compatibility considerations w.r.t. commonly-used emacs versions.

**Comment by lunaryorn** [comment]
I think I already commented, for just for reference, :-1: from me as well.  Emacs Lisp isn't CL.

**Comment by bbatsov** [comment]
I dislike the suggestion as well. The council has spoken! :-)

**Comment by wpcarro** [comment]
Probing to see if anyone has softened to this idea over the past 3 years. I like the proposal. I prefer the consistency and think this is one place Elisp could learn from CL. I think in the long run, setf will gain popularity as it abstracts away a lot of the trivia that often complicates programming tasks that are conceptually super simple.

**Comment by sebasmonia** [comment]
I reached this issue looking for reasons/info on why `setf` is not recommended style for Emacs Lisp. I think there's benefit in using the same form as CL, and the fact that `setf` is a superset of `setq` (and generates the same code for symbols).
