### ISSUE TITLE
Remind people to define a version number defconst

### ISSUE THREAD

**Issue by Bruce-Connor** [bbatsov/emacs-lisp-style-guide#32]
Besides the `;; Version: ` comment, it's useful for packages to define their version numbers as variables.
Something like the following should be enough.

    (defconst PACKAGE-version "1.3" "PACKAGE's version number.")

**Comment by bbatsov** [comment]
Ping :-) Any thoughts on this?

**Comment by dgutov** [comment]
I like the second option, naturally.

**Comment by bbatsov** [comment]
Any idea when `lm-version` was introduced?

**Comment by dgutov** [comment]
Before 1992.

**Comment by lunaryorn** [comment]
@Bruce-Connor I don't like these version constants.  These days, they are redundant at best—we have the version in package headers anyway—and wrong at worst—if they diverge from the official version in the headers.

We should really recommend `lm-version`.

**Comment by bbatsov** [comment]
Yeah, seems there's a consensus regarding this. :-)

**Comment by Bruce-Connor** [comment]
Yes. lm-version os certainly much better.
