### ISSUE TITLE
Co-editors

### ISSUE THREAD

**Issue by bbatsov** [bbatsov/emacs-lisp-style-guide#34]
@lunaryorn @purcell @Bruce-Connor @dgutov I've been pretty busy lately which has stalled the progress on this project (which I feel is very important long-term). You're all Emacs Lisp experts and can definitely help move the project forward. Are any of you willing to join as co-editors?

**Comment by lunaryorn** [comment]
@bbatsov I would not consider myself an “expert”, but I'm willing to help.  But I'm busy, too, so I can't promise anything.

**Comment by purcell** [comment]
Sure, I'm happy to join the roster of authors, but I can't commit to doing anything right away because I'm stupidly busy. :-)

**Comment by bbatsov** [comment]
Guys, just to clarify, I'm not expecting anyone to document every single good practice till the end of next week. :-) I know everyone's pretty busy and I simply hope that if more people have the power to push this forward we'll manage to go farther.

**Comment by dgutov** [comment]
@bbatsov Sure, but to similarly lower the expectations: the guide looks fine to me (I could even take out some things from Comment Annotations), and the only current proposal that looks interesting is sharp quotes.

**Comment by Bruce-Connor** [comment]
I'm happy to join as well, and the same disclaimer as everyone above also applies.
Still, I do agree with you. 5 busy editors is probably better than 1 busy editor (assuming divergences aren't numerous).

**Comment by bbatsov** [comment]
You're all collaborators now. I'm closing this ticket.
