### ISSUE TITLE
Separate sentences with _two spaces_

### ISSUE THREAD

**Issue by ruediger** [bbatsov/emacs-lisp-style-guide#36]
The "Comments" section says

> Separate sentences with one space.

This is in violation of the Emacs default settings and common coding convention.  The default value of `sentence-end-double-space` is t and most elisp code follows this behavior. It allows unambiguous distinction between sentence endings and other uses of the period.

Yes, there is a debate whether double spacing is good or bad style and the article does link to the wikipedia page about it. But this is simply not the place to have that discussion. The Emacs default settings have decided the discussion as far as common coding conventions for elisp are concerned. It seems therefore rather annoying and pointless to put personal preferences there. (The arguments against double spacing are largely exclusive for proportional fonts, which nobody uses for coding anyway.)

Therefore the comment should be changed to "Separate sentences with two spaces" or if the author really insists on personal preferences over common coding conventions then it should at least be removed.

**Comment by dgutov** [comment]
Actually, +1 from me.

It's a minor preference, there's no real need to go against the core in it.

**Comment by Bruce-Connor** [comment]
This discussion had come up on an unrelated issue but was (apparently) forgotten. As much as I prefer single-space, the core is very emphatic about double-space and we should just follow.

**Comment by bbatsov** [comment]
Yeah, we should update this. I guess I just copied it from the Clojure guide. :-)

**Comment by Bruce-Connor** [comment]
PR created.
