### ISSUE TITLE
Which is better "when-and" layout?

### ISSUE THREAD

**Issue by ReimuXMX** [bbatsov/emacs-lisp-style-guide#46]
Hello, and sorry for my poor English.

So I often write some `when-and` statements, which is better written?

1. 
``` emacs-lisp
(when (and (sth1) (sth2))
  (body))
```

2. 
``` emacs-lisp
(when (and (sth1)
           (sth2))
  (body))
```

**Comment by tumashu** [comment]
if  sth1 and sth2 is very very long, I prefer 2

**Comment by ReimuXMX** [comment]
Then……
+ A: The sth1/sth2 is very very long, but the other is very very short.
+ B: The sth1 and sht2 are both very very short.

What kind of style do you prefer in these both cases ? 

I like the 2 in B, and 1 in A now.

**Comment by ReimuXMX** [comment]
Stop this boring argument.
Boring ...
