### ISSUE TITLE
Collaborate?

### ISSUE THREAD

**Issue by alphapapa** [bbatsov/emacs-lisp-style-guide#47]
Hi Bozihdar,

I just discovered this repo.  I think something like this is definitely needed, since, e.g. I see Steve Purcell having to repeatedly give a lot of the same feedback to new package developers.  I recently started https://alphapapa.github.io/emacs-package-dev-handbook/.  It seems like we're covering some of the same ground.  Do you think we should collaborate in some way, or do you think we're addressing different issues?  I will certainly be linking to this repo in it.  :)

**Comment by bbatsov** [comment]
I'm always open to collaboration opportunities. 

Do you have anything specific in mind?

**Comment by alphapapa** [comment]
Actually, no, haha.  :)  I'll let you know if I have anything specific.
