### ISSUE TITLE
org-mode?

### ISSUE THREAD

**Issue by alexanderbarbosa** [bbatsov/emacs-lisp-style-guide#49]
Hey, I kinda feel this guide would serve emacs users better in a format that would require no additional package as dependency! 

Just a thought. :)

**Comment by Fuco1** [comment]
I'm sorry but I don't understand what the issue is here? Can you elaborate?

**Comment by AloisJanicek** [comment]
1. install emacs
2. download elisp style guide
3. install 3rd party package for markdown
4. still no syntax highlighting, no advanced navigation, etc. like in org files
--- 
The information itself presented in document is superb and useful.

Even so useful that reader would like to clone this repo for quick access and reference without going through additional steps like converting it with pandoc to org document format, tweaking source block headers to get syntax highlighted code examples and doing those steps every time when there are updates. 

(fact that those steps can be automated and done under 1 sec isn't IMHO supporting argument for not providing this document (also) in org file format.)

**Comment by Fuco1** [comment]
What package did you install for markdown? Everything works great with the `markdown-mode` I am using.

**Comment by bbatsov** [comment]
Is someone wants to tackle the conversion that'd be fine by me. I'm not a big fan of Markdown myself.
