### ISSUE TITLE
Naming convention for boolean variables

### ISSUE THREAD

**Issue by andreyorst** [bbatsov/emacs-lisp-style-guide#57]
Style guide suggest to name functions that return booleans with `p` or `-p` for "predicate", but what convention should be used for such variables, like `feature-enabled` or `feature-enabled-p`. These variables are used in predicate position in `if` or `when`, yet those aren't functions, so I'm a bit confused.

**Comment by dgutov** [comment]
I believe the convention is that `-p` is only for functions.

**Comment by andreyorst** [comment]
I've searched a bit over GitHub, and didn't found a lot of examples where boolean variables are named with `-p`: [haskell-mode](https://github.com/haskell/haskell-mode/blob/c3d3e23b7b0e99bee382b3192629584202e6613b/haskell-customize.el#L208-L212), [cling-mode](https://github.com/eiselekd/dotfiles/blob/f1577b4c63ea5279862d5b2f87db83d804bb964a/.emacs.d/lisp/lib/cling-mode/cling-customize.el#L153-L157), [parinfer-rust-mode](https://github.com/justinbarclay/parinfer-rust-mode/blob/95bf9baa6f000eb577f81ebc74d2236d8e06442b/parinfer-rust-mode.el#L104-L112).

A lot of such variables were ending with imperative word implying that some action can be taken or not depending on the value, e.g. `-enable`, `-hover`, `-format`, `-split`. `-import`

**Comment by dgutov** [comment]
Agree.
