### ISSUE TITLE
progn along with if

### ISSUE THREAD

**Issue by noorul** [bbatsov/emacs-lisp-style-guide#59]
I see that `progn` is discouraged in the style guide. I am thinking about how is the following scenario handled.

If there is more than one statement to be executed if the condition is true and otherwise.

**Comment by Fuco1** [comment]
It says:

> Don’t wrap the *else* clause

The if clause needs to be wrapped, there's no way around it.  Unless it's a single form.

**Comment by noorul** [comment]
Thanks for the clarification. Closing this.
